"""
plot_radius_sweep.py
--------------------
Reads an MSTM output file generated by a radius sweep and produces:

  1. Efficiencies vs radius  (Qext / Qabs / Qsca)
  2. S₁₁ polar diagram  —  linear and log scale
  3. Individual polar grid  —  one subplot per radius step

Usage:
    python plot_radius_sweep.py <output.dat> [config.json]

    <output.dat>   MSTM output file  (required)
    [config.json]  Simulation config (optional).
                   If provided, radius values are read from it.
                   Otherwise the x-axis shows run index.
"""

import sys
import os
import re
import json
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib.colors as mcolors
import matplotlib.cm as cm
from matplotlib.lines import Line2D


# =============================================================================
#  Global plotting style  (mirrors plot_scattering_matrix.py)
# =============================================================================
plt.rcParams.update({
    "xtick.labelsize": 16,
    "ytick.labelsize": 16,
    "axes.titlesize":  16,
    "axes.labelsize":  20,
    "legend.fontsize": 14,
})
plt.rcParams["figure.titlesize"] = 18
plt.rcParams["lines.linewidth"]  = 2

# Fixed colour palette  (same as plot_scattering_matrix.py)
C_EXT = "#1f77b4"   # blue   — Q_ext
C_ABS = "#d62728"   # red    — Q_abs
C_SCA = "#2ca02c"   # green  — Q_sca

# =============================================================================
#  Display / save behaviour
#  SHOW_ONLY = True  → save PNG files and open each figure interactively
#  SHOW_ONLY = True   → show figures interactively only, do not save any files
#  Can also be overridden at runtime with the --show-only CLI flag.
# =============================================================================
SHOW_ONLY = True


# =============================================================================
#  Utilities
# =============================================================================

def set_fig_title(fig, title: str):
    try:
        fig.canvas.manager.set_window_title(title)
    except Exception:
        pass


def auto_save_or_show(fig, name: str, save_dir: str = "."):
    """Save PNG and show interactively, unless SHOW_ONLY is True."""
    if not SHOW_ONLY:
        os.makedirs(save_dir, exist_ok=True)
        outfile = os.path.join(save_dir, f"{name}.png")
        fig.savefig(outfile, dpi=150, bbox_inches="tight")
        print(f"  -> Saved: {outfile}")
    plt.show(block=False)


# =============================================================================
#  Parsing
# =============================================================================

EFF_RE       = re.compile(r"total extinction.*efficiencies\s*\(unpol, par, perp")
EFF_RE_UNPOL = re.compile(r"total extinction.*efficiencies\s*\(unpolarized")
SCAT_RE      = re.compile(r"scattering matrix in incident plane")
THETA_HDR_RE = re.compile(r"^\s*theta\s+11\b")


def _parse_eff_line(vals):
    """Return efficiency dict from a list of 3 or 9 floats."""
    if len(vals) == 9:
        return {
            "unpol": {"Qext": vals[0], "Qabs": vals[1], "Qsca": vals[2]},
            "par":   {"Qext": vals[3], "Qabs": vals[4], "Qsca": vals[5]},
            "perp":  {"Qext": vals[6], "Qabs": vals[7], "Qsca": vals[8]},
        }
    _nan = {"Qext": np.nan, "Qabs": np.nan, "Qsca": np.nan}
    if len(vals) == 3:
        d = {"Qext": vals[0], "Qabs": vals[1], "Qsca": vals[2]}
        return {"unpol": d, "par": d.copy(), "perp": d.copy()}
    return {"unpol": _nan.copy(), "par": _nan.copy(), "perp": _nan.copy()}


def _empty_eff():
    _nan = {"Qext": np.nan, "Qabs": np.nan, "Qsca": np.nan}
    return {"unpol": _nan.copy(), "par": _nan.copy(), "perp": _nan.copy()}


def parse_runs(filepath: str) -> list:
    """
    Parse MSTM output file.  Returns a list of run dicts:
        {
          "eff":         { "unpol": {...}, "par": {...}, "perp": {...} },
          "degreeTheta": ndarray | None,
          "radianTheta": ndarray | None,
          "S11":         ndarray | None,
        }
    """
    with open(filepath, "r", errors="ignore") as fh:
        lines = fh.readlines()

    runs        = []
    pending_eff = None
    i = 0

    while i < len(lines):
        line = lines[i]

        # ── Efficiencies ──────────────────────────────────────────────────
        if EFF_RE.search(line):
            try:
                vals = list(map(float, lines[i + 1].split()))
                pending_eff = _parse_eff_line(vals)
            except (ValueError, IndexError):
                pass
            i += 2
            continue

        if EFF_RE_UNPOL.search(line):
            try:
                vals = list(map(float, lines[i + 1].split()))
                pending_eff = _parse_eff_line(vals)
            except (ValueError, IndexError):
                pass
            i += 2
            continue

        # ── Scattering matrix ─────────────────────────────────────────────
        if SCAT_RE.search(line):
            # advance to column header  "theta  11  12 ..."
            j = i + 1
            while j < len(lines) and not THETA_HDR_RE.match(lines[j]):
                j += 1
            j += 1   # first data row

            thetas, s11 = [], []
            while j < len(lines):
                stripped = lines[j].strip()
                if not stripped or stripped.startswith("*"):
                    break
                parts = stripped.split()
                try:
                    thetas.append(float(parts[0]))
                    s11.append(float(parts[1]))
                except (ValueError, IndexError):
                    break
                j += 1

            if thetas:
                theta_deg = np.array(thetas)
                runs.append({
                    "eff":         pending_eff or _empty_eff(),
                    "degreeTheta": theta_deg,
                    "radianTheta": np.deg2rad(theta_deg),
                    "S11":         np.array(s11),
                })
                pending_eff = None
            i = j
            continue

        i += 1

    # A run with only efficiency data (no scattering matrix)
    if pending_eff is not None:
        runs.append({
            "eff":         pending_eff,
            "degreeTheta": None,
            "radianTheta": None,
            "S11":         None,
        })

    return runs


# =============================================================================
#  Config / radius helpers
# =============================================================================

def load_radii_from_config(config_path: str, n_runs: int):
    """Read radius sweep values from config.json.  Returns ndarray or None."""
    if not os.path.exists(config_path):
        return None
    try:
        with open(config_path) as fh:
            cfg = json.load(fh)
        rs = cfg.get("radius_sweep", {})
        if not rs.get("enabled", False):
            return None
        radii = np.linspace(float(rs["min"]), float(rs["max"]), int(rs["n"]))
        if len(radii) != n_runs:
            print(f"  [warning] config.json has {len(radii)} steps "
                  f"but {n_runs} runs found.")
        return radii
    except Exception as exc:
        print(f"  [warning] Could not read config.json: {exc}")
        return None


def writable_dir(path: str) -> str:
    """Return path if writable, otherwise current working directory."""
    try:
        test = os.path.join(path, ".write_test")
        open(test, "w").close()
        os.remove(test)
        return path
    except OSError:
        return os.path.abspath(".")


# =============================================================================
#  Efficiencies  vs  radius
# =============================================================================

# Colour per polarization
POL_COLORS = {"unpol": "#2C7BB6", "par": "#D7191C", "perp": "#1A9641"}
POL_LABELS = {"unpol": "Unpolarized", "par": "Parallel", "perp": "Perpendicular"}
Q_STYLES   = {"Qext": "-", "Qabs": "--", "Qsca": ":"}


def plot_efficiencies(runs: list, radii: np.ndarray,
                      polarizations: list = None, save_dir: str = "."):
    """
    Three-panel subplot: one panel per efficiency (Qext, Qabs, Qsca).
    Each panel shows one curve per polarization (if available).
    """
    if polarizations is None:
        polarizations = ["unpol"]

    q_keys = ["Qext", "Qabs", "Qsca"]
    q_latex = {
        "Qext": r"$Q_\mathrm{ext}$",
        "Qabs": r"$Q_\mathrm{abs}$",
        "Qsca": r"$Q_\mathrm{sca}$",
    }

    fig, axes = plt.subplots(1, 3, figsize=(14, 4.5))

    for ax, q in zip(axes, q_keys):
        for pol in polarizations:
            values = np.array([r["eff"][pol][q] for r in runs])
            ax.plot(radii, values,
                    color=POL_COLORS[pol],
                    linestyle=Q_STYLES[q],
                    marker="o", markersize=5,
                    label=POL_LABELS[pol])
        ax.set_title(q_latex[q])
        ax.set_xlabel(r"Radius $a$ ($\mu$m)")
        ax.set_ylabel(q_latex[q])
        ax.xaxis.set_minor_locator(ticker.AutoMinorLocator())
        ax.yaxis.set_minor_locator(ticker.AutoMinorLocator())
        ax.grid(True, which="major", linestyle="--", alpha=0.5)
        ax.grid(True, which="minor", linestyle=":",  alpha=0.3)
        ax.tick_params(axis="both", which="both", direction="in")

    if len(polarizations) > 1:
        handles = [Line2D([0], [0], color=POL_COLORS[p], lw=2,
                          label=POL_LABELS[p]) for p in polarizations]
        fig.legend(handles=handles, title="Polarization",
                   loc="lower center", ncol=len(polarizations),
                   bbox_to_anchor=(0.5, -0.08), frameon=True)
    
    title = title = (
        f"Rayleigh → Mie, "
        f"$\\lambda = {520}$ nm"
    )
    title = "Efficiencies — radius sweep"
    fig.suptitle(title, fontsize=18)
    fig.tight_layout(rect=[0, 0.06, 1, 1])

    set_fig_title(fig, "Efficiencies")
    auto_save_or_show(fig, "EFF_subplots", save_dir)


# =============================================================================
#  S11 polar  —  overlay  (linear + log)
# =============================================================================

def plot_S11_polar(runs: list, radii: np.ndarray,
                   log_scale: bool = False, save_dir: str = ".",
                   plot_number: int = 8):
    """
    All S11 curves superimposed on a single polar axes.
    Colourmap: blue (smallest radius) → red (largest radius).

    Angular convention  (standard scattering diagram):
      theta = 0°    →  forward  (East / right)
      theta = ±90°  →  lateral  (North / South)
      theta = ±180° →  backward (West / left)
    """
    # keep only runs that have a scattering matrix
    valid = [(r, a) for r, a in zip(runs, radii) if r["S11"] is not None]
    if not valid:
        print("  [warning] No scattering matrix data found.")
        return

    # subsample evenly if too many curves
    if len(valid) > plot_number:
        idx    = np.linspace(0, len(valid) - 1, plot_number, dtype=int)
        valid  = [valid[i] for i in idx]

    n    = len(valid)
    cmap = cm.coolwarm
    norm = mcolors.Normalize(vmin=radii[0], vmax=radii[-1])

    fig = plt.figure(figsize=(7, 7))
    ax  = fig.add_subplot(111, projection="polar")

    # theta=0 (forward scatter) at East (right); counterclockwise — standard
    ax.set_theta_zero_location("E")
    ax.set_theta_direction(1)

    for ri, (r, a) in enumerate(valid):
        s11   = r["S11"].copy()
        theta = r["radianTheta"]

        if log_scale:
            vals = np.log10(np.clip(s11, 1e-9, None))
            vals -= vals.min()
        else:
            vals = s11

        color = cmap(norm(a))
        ax.plot(theta, vals, color=color, linewidth=1.8, alpha=0.85,
                label=f"$a$ = {a:.3f} $\\mu$m")

    # colourbar
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, pad=0.13, fraction=0.035)
    cbar.set_label(r"Radius $a$ ($\mu$m)", fontsize=14)
    cbar.set_ticks(np.linspace(radii[0], radii[-1], min(n, 6)))
    cbar.set_ticklabels(
        [f"{v:.3f}" for v in np.linspace(radii[0], radii[-1], min(n, 6))],
        fontsize=12)

    scale_tag = "log scale" if log_scale else "linear scale"
    fig.suptitle(f"$S_{{11}}$ polar — {scale_tag}", fontsize=18)

    # angle labels: 0° right = forward, 180° left = backward
    ax.set_xticks(np.deg2rad([0, 45, 90, 135, 180, 225, 270, 315]))
    ax.set_xticklabels(
        ["0°\n(fwd)", "45°", "90°", "135°",
         "180°\n(bwd)", "225°", "270°", "315°"],
        fontsize=10)

    ax.grid(True, alpha=0.3)
    plt.tight_layout()

    suffix = "S11_polar_log" if log_scale else "S11_polar_linear"
    set_fig_title(fig, f"S11 ({scale_tag})")
    auto_save_or_show(fig, suffix, save_dir)


# =============================================================================
#  S11 polar  —  individual grid
# =============================================================================

def plot_S11_grid(runs: list, radii: np.ndarray, save_dir: str = "."):
    """One polar subplot per radius step."""
    valid = [(r, a) for r, a in zip(runs, radii) if r["S11"] is not None]
    if not valid:
        print("  [warning] No scattering matrix data found.")
        return

    n    = len(valid)
    ncol = min(5, n)
    nrow = (n + ncol - 1) // ncol
    cmap = cm.coolwarm
    norm = mcolors.Normalize(vmin=radii[0], vmax=radii[-1])

    fig = plt.figure(figsize=(ncol * 3.0, nrow * 3.0))
    fig.suptitle("$S_{11}$ — individual polar plots per radius", fontsize=18)

    for idx, (r, a) in enumerate(valid):
        ax = fig.add_subplot(nrow, ncol, idx + 1, projection="polar")
        ax.set_theta_zero_location("E")
        ax.set_theta_direction(1)

        ax.plot(r["radianTheta"], r["S11"],
                color=cmap(norm(a)), linewidth=1.3)
        ax.set_title(f"$a$ = {a:.3f} $\\mu$m", fontsize=9, pad=5)
        ax.tick_params(labelleft=False, labelbottom=False)
        ax.grid(True, alpha=0.3)

    plt.tight_layout()
    set_fig_title(fig, "S11 grid")
    auto_save_or_show(fig, "S11_polar_grid", save_dir)


# =============================================================================
#  Main
# =============================================================================

def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="Plot MSTM radius-sweep results.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("dat_file",    help="MSTM output file (.dat)")
    parser.add_argument("config_file", nargs="?", default=None,
                        help="config.json with sweep parameters (optional)")
    parser.add_argument("--show-only", action="store_true",
                        help="Show figures interactively only; do not save any PNG files")
    args = parser.parse_args()

    global SHOW_ONLY
    if args.show_only:
        SHOW_ONLY = True

    dat_path    = args.dat_file
    config_path = (args.config_file
                   if args.config_file
                   else os.path.join(os.path.dirname(dat_path), "config.json"))

    if not os.path.exists(dat_path):
        print(f"Error: file not found — '{dat_path}'")
        sys.exit(1)

    print(f"Reading: {dat_path}")
    print(f"  -> Show-only mode: {SHOW_ONLY}")

    # ── Parse ────────────────────────────────────────────────────────────
    runs   = parse_runs(dat_path)
    n_runs = len(runs)

    if n_runs == 0:
        print("No efficiency or scattering matrix blocks found.")
        sys.exit(1)

    n_scat = sum(1 for r in runs if r["S11"] is not None)
    print(f"  -> {n_runs} runs  ({n_scat} with scattering matrix)")

    # ── Radii ────────────────────────────────────────────────────────────
    radii = load_radii_from_config(config_path, n_runs)
    if radii is not None:
        print(f"  -> Radii (config.json): {radii[0]:.4f} – {radii[-1]:.4f} μm")
    else:
        radii = np.linspace(1, n_runs, n_runs)
        print(f"  -> config.json not available; x-axis = run index (1–{n_runs})")

    # ── Detect polarization content ───────────────────────────────────────
    has_par_perp = any(
        abs(r["eff"]["par"]["Qext"] - r["eff"]["unpol"]["Qext"]) > 1e-10
        for r in runs
    )
    polarizations = ["unpol", "par", "perp"] if has_par_perp else ["unpol"]
    print(f"  -> Polarizations: {polarizations}")

    # ── Output directory ─────────────────────────────────────────────────
    save_dir = writable_dir(os.path.dirname(os.path.abspath(dat_path)))
    plot_dir = os.path.join(save_dir, "plots")
    os.makedirs(plot_dir, exist_ok=True)
    mpl.rcParams["savefig.directory"] = plot_dir
    print(f"  -> Saving to: {save_dir}")
    print(f"  -> Default save-image folder: {plot_dir}")

    # ── Figures ──────────────────────────────────────────────────────────
    plot_efficiencies(runs, radii, polarizations=polarizations, save_dir=save_dir)

    # Combined efficiency plot (all three Q on one axes)
    fig_c, ax_c = plt.subplots(figsize=(8, 5))
    q_latex = {"Qext": r"$Q_\mathrm{ext}$",
               "Qabs": r"$Q_\mathrm{abs}$",
               "Qsca": r"$Q_\mathrm{sca}$"}
    q_colors = {"Qext": C_EXT, "Qabs": C_ABS, "Qsca": C_SCA}
    pol_ls    = {"unpol": "-", "par": "--", "perp": ":"}
    for q in ["Qext", "Qabs", "Qsca"]:
        for pol in polarizations:
            values = np.array([r["eff"][pol][q] for r in runs])
            lbl = (f"{q_latex[q]} ({POL_LABELS[pol]})"
                   if len(polarizations) > 1 else q_latex[q])
            ax_c.plot(radii, values,
                      color=q_colors[q], linestyle=pol_ls[pol],
                      marker="o", markersize=4, label=lbl)
    ax_c.set_xlabel(r"Radius $a$ ($\mu$m)")
    ax_c.set_ylabel(f"{chr(44).join(q_latex.values())}")
    ax_c.xaxis.set_minor_locator(ticker.AutoMinorLocator())
    ax_c.yaxis.set_minor_locator(ticker.AutoMinorLocator())
    ax_c.grid(True, which="major", linestyle="--", alpha=0.5)
    ax_c.grid(True, which="minor", linestyle=":",  alpha=0.3)
    ax_c.tick_params(axis="both", which="both", direction="in")
    ax_c.legend(fontsize=13)
    title = title = (
        f"Rayleigh → Mie, "
        f"$\\lambda = {520}$ nm"
    )
    title = "Efficiencies — radius sweep"
    fig_c.suptitle(title, fontsize=18)
    fig_c.tight_layout()
    set_fig_title(fig_c, "Efficiencies combined")
    auto_save_or_show(fig_c, "EFF_combined", save_dir)

    plot_S11_polar(runs, radii, log_scale=False, save_dir=save_dir)
    plot_S11_polar(runs, radii, log_scale=True,  save_dir=save_dir)
    # plot_S11_grid(runs,  radii,                  save_dir=save_dir)

    plt.show(block=True)


if __name__ == "__main__":
    main()